### PR TITLE
Add Assignment_3 and Project_2

### PR DESCRIPTION
**Pull request by DruhanShah**

### CODE REVIEW

**Comment by b-beri** [comment]
@DruhanShah Have you checked this on your local computer?

**Review by b-beri — APPROVED** [review]

**Comment by DruhanShah** [comment]
I wasn't able to test the PDF Viewer on my local machine. I'll let know when I do

**Comment by b-beri** [comment]
Have you checked now? @DruhanShah

**Comment by DruhanShah** [comment]
Yes I have checked it and it works
I had mentioned it on Slack :sweat_smile:

**Comment by b-beri** [comment]
Sorry I have very bad memory.

**Comment by DruhanShah** [comment]
Lite no worries

**Pull request merged**
